name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 90.119.49.97 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Raspberry Pi
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no thryndil17@90.119.49.97 << 'EOF'
            cd /var/www/wow-helper
            git pull origin main
            npm install
            npm run build
            pm2 restart wow-helper || pm2 start npm --name wow-helper -- run start
          EOF
